### ISSUE TITLE
Updated to latest version (0.90); how to change the Moment.js version used?

### ISSUE THREAD

**Issue by raywu** [gdi2290/angular-momentjs#13]
Hi, I updated to the latest angular-momentjs; I'm using bower to manage dependencies. How do I update moment.js from 2.8.4 to a newer version?

<pre>
{
  "name": "magic-front-end",
  "version": "0.0.0",
  "dependencies": {
    "angular": "~1.3.8",
    "angular-moment": "~0.9.0",
    …
  }
}
</pre>
<pre>
├─┬ angular-moment#0.9.0
│ ├── angular#1.3.8 (1.3.9 available, latest is 1.4.0-build.3780+sha.1a7e9de)
│ └── moment#2.8.4 (2.9.0 available)
</pre>

**Comment by gdi2290** [comment]
Thanks for submitting an issue. This repo is way overdue on an update so I'll see what I can do tonight to  new release with updates

**Comment by raywu** [comment]
@gdi2290 Any update on this? Thanks!

**Comment by gdi2290** [comment]
I looked into the repo again and updated a few things here and there. I'm not specifying an Angular version or Moment version so angular-momentjs will use whatever version you or another module specifies. So your fix is solved be a by using resolutions in bower which will force package versions for your dependencies
```json
"resolutions": {
    "angular": "^1.3.11",
    "moment": "^2.9.0"
} 
```

**Comment by raywu** [comment]
Thanks Patrick!

**Comment by gdi2290** [comment]
no problem, thanks for submitting the issue
