### ISSUE TITLE
$momentProvider locale config

### ISSUE THREAD

**Issue by Gab-Metzger** [gdi2290/angular-momentjs#14]
Hello,

I'm french and I'm using your moment angular module.
I want to set default locale to 'fr'.
Is there an easy way to do it with the $momentProvider config ?
Something like that : 
```
$momentProvider
  .locale('fr')
```

Thanks,
Gabriel

**Comment by gdi2290** [comment]
alright you should be able to do it now with version [v0.2.0](https://github.com/gdi2290/angular-momentjs/tree/v0.2.0)

**Comment by Gab-Metzger** [comment]
Thanks for the quick fix.

I comment your last commit, I think there still is a little mistake.
I fixed it locally but my locale format doesn't seem to work.

Gabriel

**Comment by estvmachine** [comment]
Hi, i like to use this option but i dont understand how use it. I need for language or locale Spanish.
